### ISSUE TITLE
What should we remove?

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/polymer-boilerplate#1]
@zenorocha made the point that we should try to keep this boilerplate lean so that it's more generally useful. 

> for element creators, they just want to build the element and then attached it to their 3 other projects that have different tasks and etc

I agree. What should we try to remove here?
- Sass Bootstrap - should we have any Bootstrap?
- Optimization tasks - keep Vulcanize, but remove the others?
- Testing? should we prescribe Mocha out of the box like we do now or not?

Because this project is based on generator-polymer, we can always just recommend that they use that if they need more.

**Comment by zenorocha** [comment]
I would remove these Grunt tasks:
- [htmlmin](https://github.com/addyosmani/polymer-boilerplate/blob/master/Gruntfile.js#L170)
- [cssmin](https://github.com/addyosmani/polymer-boilerplate/blob/master/Gruntfile.js#L160)
- [imagemin](https://github.com/addyosmani/polymer-boilerplate/blob/master/Gruntfile.js#L150)
- [compass](https://github.com/addyosmani/polymer-boilerplate/blob/master/Gruntfile.js#L119)

And everything else that belongs to website authoring and not element authoring.

**Comment by zenorocha** [comment]
Essentially we would only need vulcanize and connect (because people need local servers to run it), but I think we need to evangelize best practices that's why JSHint, Mocha, and others are ok for me.
